
version: 0.1
 
phases:
  install:
    commands:
      - sudo apt-get install zip -y
      - echo "nothing in install"
  pre_build:
    commands:
      - echo "Cleaning..."
      - dotnet restore
  build:
    commands:
      - dotnet clean -v q
      - dotnet build
      - dotnet publish -c Release -v q
      - mkdir dist
      - rm -rf dist/*
      - zip -j dist/deploy.zip bin/Release/netcoreapp2.1/publish/*
      - aws cloudformation package --template-file lam.yaml --s3-bucket sam-ci-cd --output-template-file app-output_sam.yaml
      - aws cloudformation deploy --template-file app-output_sam.yaml --stack-name new-sam-ci --capabilities CAPABILITY_IAM
